services:
  - type: web
    name: automailer-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: $PORT
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_WEBHOOK_SECRET
        sync: false
      - key: HOLYSHEET_API_KEY
        value: Z2BhkUlsA5F-wq2GQ-g5fSYu-JgfHryt
      - key: FRONTEND_URL
        value: https://auto-mailer.vercel.app
    healthCheckPath: /health
    autoDeploy: true
